/* 
BACKGROUND
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

QUESTION
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

public class P2 extends SolutionTesting {
    //The actual solution to the problem
    final static int ACTUAL_ANSWER = 4613732;
    public static void main(String[] args) {
        EnsureSolution(Solution1(), ACTUAL_ANSWER, 1);
    }

        public static long[] Solution1() {
            long[] result = new long[2];
            long startTime = System.nanoTime();
            
            //START SOLUTION
            int totalSum = 0;

            int firstNum = 0;
            int secondNum = 1;
            int currentNum = 0; 

            while (currentNum < 4_000_000) {
                currentNum = firstNum + secondNum;
                if (currentNum % 2 == 0) {
                    totalSum += currentNum;
                }

                firstNum = secondNum;
                secondNum = currentNum;
            }
            //END SOLUTION

            long endTime = System.nanoTime();
            result[0] = totalSum;
            result[1] = (endTime - startTime);
            return result;
        }
}
